alias edit=code
alias eprof="edit ~/.profile"
alias sprof=". ~/.bash_profile"
alias nrun="npm run"
alias nruns="npm run --silent"
alias nlint="npm run lint"
alias ntest="npm test && gwip"
alias ns="test -d .meteor && meteor npm start; test ! -d .meteor && npm start"

function termtitle {
    echo -ne "\033]0;$1\007"
}
alias tt="termtitle"

alias shell="tt SHELL; meteor shell"

alias ll="ls -l"
alias lf="nrun lint:fix || eslint --fix ."
alias du="du -h -d 1"


function upitfrom {
    git checkout $1; git pull; git checkout -; git merge $1 -m "Merge branch '$1'"
}

alias gg="git grep -n"
alias ggi="git grep -i -n"
alias ggmm="git grep '<<<'"                                        # git grep merge markers
alias grl="git reset HEAD^"                                        # git reset last (soft)
alias grii="git rebase -i HEAD^^"
alias griii="git rebase -i HEAD^^^"
alias griiii="git rebase -i HEAD^^^^"
alias gro='git fetch; git reset --hard @{upstream}; git clean -f'
alias grc='git rebase --continue'
alias gpause="git commit --allow-empty -m Pause"
alias gresume="git commit --allow-empty -m Resume"
alias igrep="grep -i"
alias grepi="grep -i"
alias gb="git branch"
alias gcb="git symbolic-ref HEAD --short" # git current branch
alias glo="git fetch; git log origin/`git symbolic-ref HEAD --short`"
alias gbc="git branch --contains"
alias gbr="git fetch origin && git branch --remote"
alias gc="git clean -id"
alias gap="git add -p"
alias gad="git add . && git status"
alias gadl="git add . && git diff --cached && git status"
alias gcm="git commit -m"
alias gcamend="git commit --amend"
alias gcam="git add . && git commit -a -m"
alias gwip="git add . && git commit -a -m WIP --no-verify"
alias gcommit="git commit --no-edit"                                        # no arg commit - completes a merge
alias gcmn="git commit -n -m"
alias gcamt="git commit -a -m tweak"
alias gco="git checkout" && __git_complete gcd _git_checkout
alias gcd="git fetch && git checkout -q" && __git_complete gcd _git_checkout
alias gcdm="git checkout master"
alias gcdb="git checkout -b"
alias gcdt="git checkout --track"
alias gl1="git log -1"
alias gl2="git log -2"
alias gl3="git log -3"
alias gmergetheirs="git merge -s recursive -X theirs"
alias gs="git status"
alias gd="git diff" #&& __git_complete gd _git_checkout
alias gdc="git diff --cached"
alias gdy="git diff master@{yesterday}"
alias gpush="git push"
alias gwipush="git add . && git commit -a -m WIP --no-verify && git push"
alias gpushnv="git push --no-verify"
alias gpull="git pull"
alias gpullr="git pull --rebase"
alias grhh="git reset --hard HEAD"
alias glog="git log --pretty=format:'%h %ad %s' --date=format:'%a %b-%d %R'"
alias grb="find .git/refs/heads -type f | xargs ls -ltr | tail -7 | sed -e 's|.git/refs/heads/||g' | sort -r"
alias gsal="git stash apply stash@{0}"  # git stash apply last

git_branch_matching() {
  # pipefail: a lack of match in grep will fail the pipe
  (set -o pipefail; find .git/refs/heads | grep $1 | sed -e 's/\.git\/refs\/heads\///g') ||
  git branch -r | grep $1 | sed -e 's/origin\///g'
}
alias gbm=git_branch_matching
alias gmb=git_branch_matching

alias brake="bundle exec rake"
alias brspec="bundle exec rspec"
#alias upit="git pull && bundle && rake db:migrate db:test:prepare"
alias upit="git pull && npm install && npm test"

alias dcup="docker-compose up --allow-insecure-ssl"
alias dcpull="docker-compose pull --allow-insecure-ssl"

function tickle {
    if [ -n "$1" ] && [ ! -f "$1" ]; then
        path=$(dirname $1)
        file=$(basename $1)

        [ ! -d "$path" ] && mkdir -p $path
        /usr/bin/touch "$1"
    else
        echo "tickle will mkdir -p and touch the file at the end of the path"
        echo
        echo "Usage:"
        echo "  tickle path/to/filename.ext"
    fi
}

function touch {
    if [ "$1" == "-p" ]; then # fuck with the touch command
        if [ -n "$2" ]; then
            tickle "$2"
        else
            echo "Usage:"
            echo "  touch -p /non/existent/path/to/filename.ext"
        fi
    else # pass through to the real touch command
        /usr/bin/touch "$@"
    fi
}

alias sshadda="ssh-add -A"
alias laststash="git stash apply stash@{0}"
alias chromedebug="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222"
