alias edit=subl
alias eprof="edit ~/.profile"
alias sprof=". ~/.bash_profile"
alias nrun="npm run"
alias ntest="npm test"
alias nstart="npm start"
alias ns="(([ -f package.json ] || [ -f ../package.json ]) && npm start) || ([ -d .meteor ] && meteor) || meteor test-packages ./"

alias ll="ls -l"

alias gg="git grep"
alias ggi="git grep -i"
alias gb="git branch"
alias gbr="git fetch origin && git branch --remote"
alias gc="git clean -id"
alias gap="git add -p"
alias gad="git add . && git status"
alias gca="git commit -a"
alias gcm="git commit -m"
alias gcmn="git commit -n -m"
alias gcam="git commit -a -m"
alias gcamt="git commit -a -m tweak"
alias gcd="git fetch && git checkout -q" && __git_complete gcd _git_checkout
alias gcdm="git checkout master"
alias gcdb="git checkout -b"
alias gcdt="git checkout --track"
alias gl1="git log -1"
alias gl2="git log -2"
alias gl3="git log -3"
alias gmergetheirs="git merge -s recursive -X theirs"
alias gs="git status"
alias gd="git diff" #&& __git_complete gd _git_checkout
alias gdc="git diff --cached"
alias gdy="git diff master@{yesterday}"
alias gpush="git push"
alias gpull="git pull"
alias gpullr="git pull --rebase"
alias grhh="git reset --hard HEAD"
alias brake="bundle exec rake"
alias brspec="bundle exec rspec"
#alias upit="git pull && bundle && rake db:migrate db:test:prepare"
alias upit="git pull && npm install && npm test"

alias dcup="docker-compose up --allow-insecure-ssl"
alias dcpull="docker-compose pull --allow-insecure-ssl"

function tickle {
    if [ -n "$1" ] && [ ! -f "$1" ]; then
        path=$(dirname $1)
        file=$(basename $1)

        [ ! -d "$path" ] && mkdir -p $path
        /usr/bin/touch "$1"
    else
        echo "tickle will mkdir -p and touch the file at the end of the path"
        echo
        echo "Usage:"
        echo "  tickle path/to/filename.ext"
    fi
}

function touch {
    if [ "$1" == "-p" ]; then # fuck with the touch command
        if [ -n "$2" ]; then
            tickle "$2"
        else
            echo "Usage:"
            echo "  touch -p /non/existent/path/to/filename.ext"
        fi
    else # pass through to the real touch command
        /usr/bin/touch "$@"
    fi
}

function termtitle {
    echo -ne "\033]0;$1\007"
}
alias tt="termtitle"
